
class Mouse:
    VK_LBUTTON = 0x1                        # Linker Mousebutton
    VK_RBUTTON = 0x2                        # Right Mousebutton
    VK_MBUTTON = 0x4                        # Middle Mousebutton
    VK_BACK = 0x8                           # Backspace Button
    VK_TAB = 0x9                            # Tab Button
    VK_CLEAR = 0xc                          # Numpad 5
    VK_RETURN = 0xd                         # Enter Button
    VK_SHIFT = 0x10                         # Shift Button
    VK_CONTROL = 0x11                       # STRG Button
    VK_MENU = 0x12                          # Alt Button
    VK_PAUSE = 0x13                         # Pause / Untbr
    VK_CAPITAL = 0x14                       # Caps Lock Button
    VK_ESCAPE = 0x1b                        # Escape Button
    VK_SPACE = 0x20                         # Space / Leertaste
    VK_PRIOR = 0x21                         # PageUp / Bild
    VK_NEXT = 0x22                          # PageDown / Bild
    VK_END = 0x23                           # Ende
    VK_HOME = 0x24                          # Home / Pos1
    VK_LEFT = 0x25                          # Left Arrow Button
    VK_UP = 0x26                            # Up Arrow Button
    VK_RIGHT = 0x27                         # Right Arrow Button
    VK_DOWN = 0x28                          # Down Arrow Button
    VK_PRINT = 0x2a                         # Drucken(Nokia Tastaturen)
    VK_SNAPSHOT = 0x2c                      # Drucken / S - Abf
    VK_INSERT = 0x2d                        # Insert Button
    VK_DELETE = 0x2e                        # Delete Button
    VK_HELP = 0x2f                          # Help Button
    VK_0 = 0x30                             # Button 0
    VK_1 = 0x31                             # Button 1
    VK_2 = 0x32                             # Button 2
    VK_3 = 0x33                             # Button 3
    VK_4 = 0x34                             # Button 4
    VK_5 = 0x35                             # Button 5
    VK_6 = 0x36                             # Button 6
    VK_7 = 0x37                             # Button 7
    VK_8 = 0x38                             # Button 8
    VK_9 = 0x39                             # Button 9
    VK_A = 0x41                             # Button A
    VK_B = 0x42                             # Button B
    VK_C = 0x43                             # Button C
    VK_D = 0x44                             # Button D
    VK_E = 0x45                             # Button E
    VK_F = 0x46                             # Button F
    VK_G = 0x47                             # Button G
    VK_H = 0x48                             # Button H
    VK_I = 0x49                             # Button I
    VK_J = 0x4a                             # Button J
    VK_K = 0x4b                             # Button K
    VK_L = 0x4c                             # Button L
    VK_M = 0x4d                             # Button M
    VK_N = 0x4e                             # Button N
    VK_O = 0x4f                             # Button O
    VK_P = 0x50                             # Button P
    VK_Q = 0x51                             # Button Q
    VK_R = 0x52                             # Button R
    VK_S = 0x53                             # Button S
    VK_T = 0x54                             # Button T
    VK_U = 0x55                             # Button U
    VK_V = 0x56                             # Button V
    VK_W = 0x57                             # Button W
    VK_X = 0x58                             # Button X
    VK_Y = 0x59                             # Button Y
    VK_Z = 0x5a                             # Button Z
    VK_STARTKEY = 0x5b                      # Start Button
    VK_CONTEXTKEY = 0x5d                    # Context Button
    VK_NUMPAD0 = 0x60                       # Numpad 0
    VK_NUMPAD1 = 0x61                       # Numpad 1
    VK_NUMPAD2 = 0x62                       # Numpad 2
    VK_NUMPAD3 = 0x63                       # Numpad 3
    VK_NUMPAD4 = 0x64                       # Numpad 4
    VK_NUMPAD5 = 0x65                       # Numpad 5
    VK_NUMPAD6 = 0x66                       # Numpad 6
    VK_NUMPAD7 = 0x67                       # Numpad 7
    VK_NUMPAD8 = 0x68                       # Numpad 8
    VK_NUMPAD9 = 0x69                       # Numpad 9
    VK_MULTIPLY = 0x6a                      # Numpad Multiply (*)
    VK_ADD = 0x6b                           # Numpad Add (+)
    VK_SUBTRACT = 0x6d                      # Numpad Subtract (-)
    VK_DECIMAL = 0x6e                       # Numpad Decimal (,)
    VK_DIVIDE = 0x6f                        # Numpad Divide (/)
    VK_F1 = 0x70                            # F1 Button
    VK_F2 = 0x71                            # F2 Button
    VK_F3 = 0x72                            # F3 Button
    VK_F4 = 0x73                            # F4 Button
    VK_F5 = 0x74                            # F5 Button
    VK_F6 = 0x75                            # F6 Button
    VK_F7 = 0x76                            # F7 Button
    VK_F8 = 0x77                            # F8 Button
    VK_F9 = 0x78                            # F9 Button
    VK_F10 = 0x79                           # F10 Button
    VK_F11 = 0x7a                           # F11 Button
    VK_F12 = 0x7b                           # F12 Button
    VK_F13 = 0x7c                           # F13
    VK_F14 = 0x7d                           # F14 Button
    VK_F15 = 0x7e                           # F15 Button
    VK_F16 = 0x7f                           # F16 Button
    VK_F17 = 0x80                           # F17 Button
    VK_F18 = 0x81                           # F18 Button
    VK_F19 = 0x82                           # F19 Button
    VK_F20 = 0x83                           # F20 Button
    VK_F21 = 0x84                           # F21 Button
    VK_F22 = 0x85                           # F22 Button
    VK_F23 = 0x86                           # F23 Button
    VK_F24 = 0x87                           # F24 Button
    VK_NUMLOCK = 0x90                       # Numlock Button
    VK_OEM_SCROLL = 0x91                    # Scroll Lock Button
    VK_LSHIFT = 0xa0                        # Left Shift Button
    VK_RSHIFT = 0xa1                        # Right Shift Button
    VK_LCONTROL = 0xa2                      # Left Control Button
    VK_RCONTROL = 0xa3                      # Right Control Button
    VK_LMENU = 0xa4                         # Left Alt Button
    VK_RMENU = 0xa5                         # Right Alt Button
    VK_OEM_1 = 0xba                         # ; Button
    VK_OEM_PLUS = 0xbb                      # " Button
    VK_OEM_COMMA = 0xbc                     # , Button
    VK_OEM_MINUS = 0xbd                     # - Button
    VK_OEM_PERIOD = 0xbe                    # . Button
    VK_OEM_2 = 0xbf                         # / Button
    VK_OEM_3 = 0xc0                         # ` Button
